"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Pomodoro.py']
DATA_FILES = ['tomato.png']
OPTIONS = {'iconfile': '/Users/achimsondermann/PycharmProjects/pomodoro-start/tomato.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
